# -*- coding: utf-8 -*-
"""solution.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LSvtJnoyM0g4_Taq7C0kTJcT4qeFaqxL
"""

import numpy as np

class NN(object):
    def __init__(self,
                 hidden_dims=(512, 256),
                 n_classes=10,
                 epsilon=1e-6,
                 lr=7e-4,
                 batch_size=1000,
                 seed=None,
                 activation="relu",
                 init_method="glorot"
                 ):

        self.hidden_dims = hidden_dims
        self.n_hidden = len(hidden_dims)
        self.datapath = datapath
        self.n_classes = n_classes
        self.lr = lr
        self.batch_size = batch_size
        self.init_method = init_method
        self.seed = seed
        self.activation_str = activation
        self.epsilon = epsilon

        self.train_logs = {'train_accuracy': [], 'validation_accuracy': [], 'train_loss': [], 'validation_loss': []}

        if datapath is not None:
            u = pickle._Unpickler(open(datapath, 'rb'))
            u.encoding = 'latin1'
            self.train, self.valid, self.test = u.load()
        else:
            self.train, self.valid, self.test = None, None, None

    def initialize_weights(self, dims):
        if self.seed is not None:
            np.random.seed(self.seed)

        self.weights = {}
        # self.weights is a dictionary with keys W1, b1, W2, b2, ..., Wm, Bm where m - 1 is the number of hidden layers
        all_dims = [dims[0]] + list(self.hidden_dims) + [dims[1]]

        for layer_n in range(1, self.n_hidden + 2):
            limites_distribution = 1 / ((all_dims[layer_n-1])**(1/2))

            self.weights[f"W{layer_n}"] = np.random.uniform(low=(-limites_distribution), high=limites_distribution, size=(all_dims[layer_n - 1], all_dims[layer_n]))
            self.weights[f"b{layer_n}"] = np.zeros((1, all_dims[layer_n]))

    def relu(self, x, grad=False):
        if grad:
            return x > 0
            pass
        return x * (x > 0)
        pass
        return 0

    def sigmoid(self, x, grad=False):
        f = 1/(1 + np.exp(-x))
        if grad:
            return f * (1 - f)
            pass
        return f
        pass
        return 0

    def tanh(self, x, grad=False):
        x_tanh = (np.exp(x)-np.exp(-x))/(np.exp(x)+np.exp(-x))
        if grad:
            return (1 - x_tanh**2)
            pass
        return x_tanh
        pass
        return 0

    def activation(self, x, grad=False):
        if self.activation_str == "relu":
            return self.relu(x,grad)
            pass
        elif self.activation_str == "sigmoid":
            return self.sigmoid(x,grad)
            pass
        elif self.activation_str == "tanh":
            return self.tanh(x,grad)
            pass
        else:
            raise Exception("invalid")
        return 0

    def softmax(self, x):
        # Remember that softmax(x-C) = softmax(x) when C is a constant.
        e_xi = np.exp(x - np.max(x))
        sum_exj = e_xi.sum(axis=-1)
        if len(e_xi.shape) != 1:
          sum_exj = sum_exj[:, np.newaxis]

        a = e_xi / sum_exj


        return a

    def forward(self, x):
        cache = {"Z0": x}

        for layer_n in range(1, self.n_hidden + 2):

            cache[f"A{layer_n}"] = np.dot(cache[f"Z{layer_n-1}"],(self.weights[f"W{layer_n}"])) + self.weights[f"b{layer_n}"]
            if layer_n != (self.n_hidden + 1):
              cache[f"Z{layer_n}"] = self.activation(cache[f"A{layer_n}"])
              self.os = softmax(self.oa)
            else:
              self.os = softmax(self.oa)

        return cache


    def backward(self, cache, labels):
        output = cache[f"Z{self.n_hidden + 1}"]
        grads = {}
        
        for layer_n in range(1, self.n_hidden + 2):
            n = self.n_hidden + 2 - layer_n

            if n == self.n_hidden + 1:
              grads[f"dA{n}"] = output - labels

            else:
              grads[f"dZ{n}"] = np.dot(grads[f"dA{n+1}"],np.transpose(self.weights[f"W{n+1}"]))
              grads[f"dA{n}"] = np.multiply(grads[f"dZ{n}"],self.activation(cache[f"A{n}"]))

            grads[f"dW{n}"] = np.dot(np.transpose(cache[f"Z{n-1}"]),grads[f"dA{n}"])
            grads[f"db{n}"] = np.sum(grads[f"dA{n}"],axis=0)
        return grads

    def update(self, grads):
        for layer in range(1, self.n_hidden + 2):
            self.weights[f"W{layer}"] += self.lr*(grads[f"dW{layer}"])
            self.weights[f"b{layer}"] += self.lr*(grads[f"db{layer}"])

    def one_hot(self, y):
        new_one_hot = np.zeros((len(y),np.max(y)+1))
        for i in range(len(y)):
          new_one_hot[i][y[i]] = 1
        return new_one_hot


    def loss(self, prediction, labels):
        prediction[np.where(prediction < self.epsilon)] = self.epsilon
        prediction[np.where(prediction > 1 - self.epsilon)] = 1 - self.epsilon
        return predi

    def compute_loss_and_accuracy(self, X, y):
        one_y = self.one_hot(y)
        cache = self.forward(X)
        predictions = np.argmax(cache[f"Z{self.n_hidden + 1}"], axis=1)
        accuracy = np.mean(y == predictions)
        loss = self.loss(cache[f"Z{self.n_hidden + 1}"], one_y)
        return loss, accuracy, predictions

    def train_loop(self, n_epochs):
        X_train, y_train = self.train
        y_onehot = self.one_hot(y_train)
        dims = [X_train.shape[1], y_onehot.shape[1]]
        self.initialize_weights(dims)

        n_batches = int(np.ceil(X_train.shape[0] / self.batch_size))

        for epoch in range(n_epochs):
            for batch in range(n_batches):
                minibatchX = X_train[self.batch_size * batch:self.batch_size * (batch + 1), :]
                minibatchY = y_onehot[self.batch_size * batch:self.batch_size * (batch + 1), :]
                pass

            X_train, y_train = self.train
            train_loss, train_accuracy, _ = self.compute_loss_and_accuracy(X_train, y_train)
            X_valid, y_valid = self.valid
            valid_loss, valid_accuracy, _ = self.compute_loss_and_accuracy(X_valid, y_valid)

            self.train_logs['train_accuracy'].append(train_accuracy)
            self.train_logs['validation_accuracy'].append(valid_accuracy)
            self.train_logs['train_loss'].append(train_loss)
            self.train_logs['validation_loss'].append(valid_loss)

        return self.train_logs